FORMAT: 1A
HOST: https://devrant.com/api

# devRant Avatar API

This is the unofficial documentation for the devRant avatar APIs.

**Note:**<br>
All *POST* requests are done with header application/x-form-urlencoded, API blueprint does not support *POST* request documentation yet

***POST requests will not work in playground***

Documentation was written by [@OmerFlame](https://github.com/OmerFlame)

Find an awesome-list [here](https://github.com/devRant-Community/awesome-devrant)

:[Build Avatar Preivews](references/build_avatar.apib)

:[Update Avatar Data](references/update_avatar_data.apib)

# Data Structures